version: 1
disable_existing_loggers: False

root:
  handlers: [default]
  level: INFO

loggers:
  uvicorn:
    handlers: [default]
    level: INFO
    propagate: False
  uvicorn.error:
    level: INFO
  uvicorn.access:
    handlers: [access]
    level: INFO
    propagate: False

handlers:
  default:
    class: logging.StreamHandler
    formatter: default
    stream: ext://sys.stderr
  access:
    class: logging.StreamHandler
    formatter: access
    stream: ext://sys.stdout

formatters:
  default:
    (): uvicorn.logging.DefaultFormatter
    fmt: "%(asctime)s %(levelprefix)s %(name)s - %(message)s"
    use_colors: true
  access:
    (): uvicorn.logging.AccessFormatter
    fmt: '%(asctime)s %(levelprefix)s %(client_addr)s - "%(request_line)s" %(status_code)s'
    use_colors: true