[DEBUG]
log_level = 10

[mongo]
uri = 'mongodb://localhost:27017'
database = 'demo'
max_pool_size = 5
min_pool_size = 0

[ws_client]
uri = 'ws://localhost:8090'

[sse_client]
uri = 'http://localhost:8091'


[redis_client]
uri = 'http://localhost:6379'


[kafka_client]
uri = 'http://localhost:9092'


[elasticsearch_client]
uri = 'http://localhost:8092'


[openai]
secret_key = 'xxx'


[ORIGIN]
allowed = ['*']


[JWT]
PRIVATE_KEY = "09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7"
PUBLIC_KEY = "09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7"
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 30